<a href="https://colab.research.google.com/github/HazSyl1/PyTorch-Intro/blob/main/Py_Torch_Intro_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.empty(1))

tensor([-2.4311e+20])


In [3]:
print(torch.empty(3))

tensor([1.5365e+03, 3.3052e-41, 4.6404e-17])


In [4]:
print(torch.empty(2,3))

tensor([[-6.3348e-35,  3.3057e-41, -6.3349e-35],
        [ 3.3057e-41,  1.4013e-45,  7.0065e-45]])


In [5]:
print(torch.rand(5,3))

tensor([[0.7311, 0.6784, 0.5969],
        [0.7906, 0.0348, 0.5724],
        [0.7010, 0.7177, 0.9693],
        [0.2459, 0.0205, 0.4784],
        [0.6746, 0.4024, 0.8552]])


In [7]:
print(torch.zeros(5,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
print(torch.ones(5,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x=torch.zeros(5,3)
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [12]:
print(x.dtype)

torch.float32


In [13]:
x=torch.zeros(5,3, dtype=torch.float16)
print(x.dtype)

torch.float16


In [14]:
x=torch.tensor([5.5,3])
print(x,x.dtype)

tensor([5.5000, 3.0000]) torch.float32


In [15]:
x=torch.tensor([5.5,3] , requires_grad=True)
print(x)
#gradients are req , for optimizing

tensor([5.5000, 3.0000], requires_grad=True)


In [18]:
x=torch.ones(2,2)
y=torch.rand(2,2)

z=x*y

print(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8296, 0.9383],
        [0.6690, 0.9273]])
tensor([[0.8296, 0.9383],
        [0.6690, 0.9273]])


In [20]:
torch.add(x,y)

tensor([[1.8296, 1.9383],
        [1.6690, 1.9273]])

In [21]:
y.add_(x)

tensor([[1.8296, 1.9383],
        [1.6690, 1.9273]])

In [25]:
x=torch.rand(5,3)
print(x)
print(x[:,0])
print(x[0,:])
print(x[1,1].item())

tensor([[0.6395, 0.8689, 0.7616],
        [0.6249, 0.6489, 0.7051],
        [0.8442, 0.7969, 0.1086],
        [0.1033, 0.6783, 0.7858],
        [0.1220, 0.8287, 0.2910]])
tensor([0.6395, 0.6249, 0.8442, 0.1033, 0.1220])
tensor([0.6395, 0.8689, 0.7616])
0.6488754153251648


In [27]:
#reshape
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size())
print(y.size())
print(z.size())


torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [28]:
a=torch.ones(5)
b=a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [30]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
c=torch.tensor(a)
print(a,b,c)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64) tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [27]:
# c does not gets modified but b does

In [31]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x=torch.rand(2,2).to(device) #move tensors to GPU device
#x=x.to('cpu')
#x=x.to('cuda')

x=torch.rand(2,2,device=device) # Directly creating them on the GPU
# ^quick as the above one requires the creation to be done on the
# CPU and then transfer it to the GPU

In [33]:
x=torch.randn(3 , requires_grad=True)
y=x+2

print(x)
print(y)
print(y.grad_fn)

tensor([1.6263, 0.4391, 0.1880], requires_grad=True)
tensor([3.6263, 2.4391, 2.1880], grad_fn=<AddBackward0>)


In [34]:
z=y*y*3
print(z)
z=z.mean()
print(z)

tensor([39.4511, 17.8484, 14.3622], grad_fn=<MulBackward0>)
tensor(23.8872, grad_fn=<MeanBackward0>)


In [35]:
print(x.grad)
z.backward()
print(x.grad) #dz/dx


None
tensor([7.2527, 4.8783, 4.3760])


In [36]:
a=torch.randn(2,2)
b=(a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

False
None


In [37]:
a.requires_grad_(True)
b=(a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

True


In [39]:
b=a.detach()
print(a.requires_grad)
print(b.requires_grad)

True
False


In [40]:
a=torch.randn(2,2 ,requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
  b=a **2
  print(b.requires_grad)

True
False


In [41]:
#GRADIENT DESCENT AUTOGRAD


In [48]:
f= 2*x

X=torch.tensor([1,2,3,4,5,6,7,8] , dtype= torch.float32)
y=torch.tensor([2,4,6,8,10,12,14,16] , dtype=torch.float32)

w=torch.tensor(0.0 , dtype=torch.float32 , requires_grad=True)
#(weights)

def forward(x):
  return w*x
def loss(y,y_pred):
  return((y_pred-y)**2).mean()

X_test=5.0

print(f'Prediction before training: f({X_test} = {forward(X_test).item():.3f})')



Prediction before training: f(5.0 = 0.000)


In [50]:
#Training

learning_rate = 0.01
n_epoch= 100

for epoch in range(n_epoch):
  #predict = forward pass
  y_pred=forward(X)

  #loss
  l=loss(y,y_pred)

  # calculate gradient
  l.backward()

  #Update weights
  #w.data=w.data-learning_rate *w.grad

  with torch.no_grad():
    w-= learning_rate * w.grad
  #zero the gradien after update
  w.grad.zero_()

  if (epoch+1) % 10 ==0:
    print(f"Epoch {epoch+1}:w={w.item():.3f}, loss={l.item():.3f}")

print(f"Prediction after training: f({X_test})= {forward(X_test).item():.3f}")




Epoch 10:w=2.000, loss=0.000
Epoch 20:w=2.000, loss=0.000
Epoch 30:w=2.000, loss=0.000
Epoch 40:w=2.000, loss=0.000
Epoch 50:w=2.000, loss=0.000
Epoch 60:w=2.000, loss=0.000
Epoch 70:w=2.000, loss=0.000
Epoch 80:w=2.000, loss=0.000
Epoch 90:w=2.000, loss=0.000
Epoch 100:w=2.000, loss=0.000
Prediction after training: f(5.0)= 10.000


In [51]:
#We dont need to do this shit
#WE CAN JUST USE LOSS FN AND OPTIMIZER


In [57]:
l=0

In [54]:
import torch.nn as nn

X=torch.tensor([[1],[2],[3],[4],[5],[6],[7],[8]],dtype=torch.float32)
Y=torch.tensor([[2],[4],[6],[8],[10],[12],[14],[16]],dtype=torch.float32)

n_samples , n_features=X.shape
print(X.shape)

torch.Size([8, 1])


In [55]:
X_test = torch.tensor([5] ,dtype=torch.float32)


In [60]:
#Design Model , forward pass it should be . . . .
#Here we could use the inbuilt

class LinearRegression(nn.Module):
  def __init__(self,input_dim,output_dim):
    super(LinearRegression,self).__init__()
    #define differnet layers
    self.lin =nn.Linear(input_dim,output_dim)

  def forward(self,x):
    #We apply the layer
    return self.lin(x)

#creating model instance

input_size , output_size = n_features,n_features

model = LinearRegression(input_size,output_size)
print(f"Prediction before training:f({X_test.item()})={model(X_test).item()}")

#2. Define loss and optimizer

learning_rate=0.01
n_epoch=100

loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

#3Training Loop
for epoch in range(n_epoch):
  y_predict=model(X)

  l=loss(Y,y_predict)

  l.backward()

  optimizer.step()

  optimizer.zero_grad()

  if(epoch+1) %10 ==0:
    w,b=model.parameters()
    print('epoch',epoch+1 , ': w=',w[0][0].item(), 'loss =',l.item())

print(f"Prediction after training : f({X_test.item()})={model(X_test).item()}")


Prediction before training:f(5.0)=3.6543102264404297
epoch 10 : w= 1.8319789171218872 loss = 0.18373993039131165
epoch 20 : w= 1.8392527103424072 loss = 0.16955554485321045
epoch 30 : w= 1.845556616783142 loss = 0.15651851892471313
epoch 40 : w= 1.85161292552948 loss = 0.14448381960391998
epoch 50 : w= 1.8574317693710327 loss = 0.13337451219558716
epoch 60 : w= 1.8630224466323853 loss = 0.1231192871928215
epoch 70 : w= 1.8683937788009644 loss = 0.11365273594856262
epoch 80 : w= 1.8735547065734863 loss = 0.10491402447223663
epoch 90 : w= 1.878512978553772 loss = 0.09684719145298004
epoch 100 : w= 1.8832769393920898 loss = 0.08940069377422333
Prediction after training : f(5.0)=10.072637557983398
